name: Build and Deploy
on:
  push:
    branches:
      - dev
jobs:
  deployment_job:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    name: Build And Deploy Lawhaty Backend Dev
    steps:
    - uses: actions/checkout@v3

    - name: SSH
      id:  Build_Lawhaty_backend_dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/forge/lawhaty/dev/lawhaty-backend
          # Check if there are local changes that would be overwritten by merge
          if git diff --quiet; then
              echo "No local changes. Pulling changes..."
              git pull origin dev
          else
             # If there are local changes, find the conflicting files
             conflicting_files=$(git diff --name-only)
             echo "Local changes detected in the following files:"
             echo "$conflicting_files"
             # Remove conflicting files and pull again
             echo "Removing conflicting files and pulling again..."
             rm $conflicting_files
             git pull origin dev
          fi
          /home/forge/.nvm/versions/node/v16.14.0/bin/pnpm install
          /home/forge/.nvm/versions/node/v16.14.0/bin/pnpm run prisma:schema
          /home/forge/.nvm/versions/node/v16.14.0/bin/pnpm run prisma:deploy
          /home/forge/.nvm/versions/node/v16.14.0/bin/pnpm run prisma:generate
          /home/forge/.nvm/versions/node/v16.14.0/bin/pnpm run prisma:seed
          /home/forge/.nvm/versions/node/v16.14.0/bin/pnpm run build
          pm2 reload Lawhaty

    - uses: act10ns/slack@v1
      with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#projects-devops'
      if: always()
